# Uncomment this line to define a global platform for your project
platform :ios, '9.2'
use_frameworks!

target 'Label' do
  pod 'Stripe'
  pod 'PayPal-iOS-SDK'
  pod 'PMAlertController'
  pod 'Alamofire', '~> 4.0'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift5'
  # pod 'MotionAnimation', :git => 'https://github.com/cristipetra/MotionAnimation.git', :branch => 'swift4'
  pod 'Jelly'
  pod 'ElasticTransition', :git => 'https://github.com/deejeay143/ElasticTransition.git', :branch => 'master'
  pod 'Toast-Swift', '~> 5.0.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SwiftDate', '~> 6.0.0'
  pod 'GzipSwift'

  target 'LabelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
