# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'Label' do
  pod 'Stripe'
  pod 'PayPal-iOS-SDK'
  pod 'PMAlertController'
  pod 'Alamofire', '~> 4.0'
  pod 'AlamofireImage', '~> 3.1'
  pod 'SwiftyJSON'
  pod 'NVActivityIndicatorView'
  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift3'
  pod 'Jelly'
  pod 'ElasticTransition'
  pod 'Toast-Swift', '~> 3.0.1'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftDate', '~> 4.3.0'

  target 'LabelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
